/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const initialize: () => any;
export const send_nostr_msg: (a: number, b: number) => any;
export const fetch_and_decrypt_local_messages: () => any;
export const save_image: (a: number, b: number, c: number, d: number) => any;
export const fetch_images: () => any;
export const fetch_nostr_events: (a: number, b: number) => any;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const ring_core_0_17_14__bn_mul_mont: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const closure1095_externref_shim: (a: number, b: number, c: any) => void;
export const closure1177_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb8e4f6826d79d583: (a: number, b: number) => void;
export const closure2297_externref_shim: (a: number, b: number, c: any) => void;
export const closure2682_externref_shim: (a: number, b: number, c: any) => void;
export const closure4216_externref_shim_multivalue_shim: (a: number, b: number, c: any) => [number, number];
export const __externref_table_dealloc: (a: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h609308ea8ef84ba2: (a: number, b: number) => void;
export const closure4823_externref_shim: (a: number, b: number, c: any) => void;
export const closure5716_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
